version: '3'

services:
  traefik:
    image: traefik:2.2
    container_name: "traefik"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./docker-volumes/traefik.yml:/etc/traefik/traefik.yml
      - ./docker-volumes/acme.json:/etc/traefik/acme/acme.json

  nextcloud-postgres:
    # https://hub.docker.com/_/postgres
    image: postgres:12-alpine
    container_name: "nextcloud-postgres"
    restart: unless-stopped
    volumes:
      - ./docker-volumes/postgres/:/var/lib/postgresql/data:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${repo.vault.password_for("nextcloud postgress")}

  nextcloud-redis:
    # https://hub.docker.com/_/redis
    image: redis:alpine
    container_name: "nextcloud-redis"
    restart: unless-stopped

  nextcloud:
    # https://hub.docker.com/_/nextcloud
    image: nextcloud:18-apache
    container_name: "nextcloud"
    restart: unless-stopped
    depends_on:
      - nextcloud-postgres
      - nextcloud-redis
    volumes:
      - ./docker-volumes/nextcloud/html/:/var/www/html/:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=${repo.vault.human_password_for("nextcloud admin")}
      - POSTGRES_HOST=nextcloud-postgres
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${repo.vault.password_for("nextcloud postgress")}
      - NEXTCLOUD_HOSTNAME=${NEXTCLOUD_DOMAIN}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_DOMAIN} localhost
      - REDIS_HOST=nextcloud-redis
      - OVERWRITEPROTOCOL=https
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_DOMAIN}`)"
      - "traefik.http.routers.nextcloud.entrypoints=web"
      - "traefik.http.routers.nextcloud.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`${NEXTCLOUD_DOMAIN}`)"
      - "traefik.http.routers.nextcloud-secure.entrypoints=web-secure"
      - "traefik.http.routers.nextcloud-secure.tls.certResolver=default"
      - "traefik.http.routers.nextcloud-secure.tls=true"
      - "traefik.http.routers.nextcloud-secure.middlewares=nextcloudheaders@docker,nextcloud-dav@docker"
      - "traefik.http.middlewares.nextcloudheaders.headers.customRequestHeaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.nextcloudheaders.headers.accessControlAllowOrigin=*"
      - "traefik.http.middlewares.nextcloud-dav.replacepathregex.regex=^/.well-known/ca(l|rd)dav"
      - "traefik.http.middlewares.nextcloud-dav.replacepathregex.replacement=/remote.php/dav/"




