entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"

providers:
  docker:
    watch: true
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true
    filename: dynamic.yml

certificatesResolvers:
  default:
    acme:
      email: webmaster@${NEXTCLOUD_DOMAIN}
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

api:
  insecure: true
  dashboard: true

log:
  level: INFO

accessLog:
  filePath: /dev/stdout

global:
  sendAnonymousUsage: false
